import { rankCities, normalizeProfile, buildPortrait, JOY_CONFIG, buildTrialPlan } from '/core/matcher.mjs';
import { getNextQuestion, applyAnswer, applyFeedback } from '/core/questions.mjs';

const KEY='city-matchmaker-v1',BACKUP=KEY+'-backup';
const freshProfile=()=>normalizeProfile({guide:'dog',nickname:'',school:'',major:'',mbti:'',stage:'graduating',industry:'tech'});
const freshState=()=>({version:2,route:'profile',page:0,round:1,profile:freshProfile(),firstCityId:null,firstProfile:null,selectedCityId:null,answerLog:[],feedbackReason:null,feedbackPicking:null});
let state=freshState(),cities=[],storageAvailable=true,toastTimer,shareURL=null,dialogOpener=null;
const main=document.getElementById('main');
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeURL=s=>{try{const u=new URL(s);return ['https:','http:'].includes(u.protocol)?u.href:'#';}catch{return '#';}};
const dimensionNames=Object.fromEntries(JOY_CONFIG.dimensions.map(d=>[d.id,d.label]));
const climateNames={heat:'持续炎热',cold:'冬天太冷',humidity:'潮湿闷热'};
const feedNames={heart:'这里让我心动',unbearable:'有一点我受不了',unsure:'还没感觉','not-this-city':'这座不考虑'};
const guideName=()=>JOY_CONFIG.guides[state.profile.guide].label;
const dog=(cat,dog)=>state.profile.guide==='dog'?dog:cat;
function readState(){try{const raw=localStorage.getItem(KEY),s=JSON.parse(raw||'null');if(!s?.profile||![1,2].includes(s.version))return;
 const p=normalizeProfile(s.profile);for(const k of ['nickname','school','major','mbti','currentCity','homeCity'])p[k]=typeof p[k]==='string'?p[k].slice(0,80):'';
 if(s.version===1){state={...freshState(),profile:p};try{localStorage.setItem(BACKUP,raw);}catch{storageAvailable=false;}return;}
 state={...freshState(),...s,profile:p,route:['profile','portrait','first','question','result'].includes(s.route)?s.route:'profile',page:Number.isInteger(s.page)?Math.min(6,Math.max(0,s.page)):0,answerLog:Array.isArray(s.answerLog)?s.answerLog:[],feedbackPicking:null};
 }catch{storageAvailable=false;}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{storageAvailable=false;}}
function toast(text){const el=document.getElementById('toast');el.textContent=text;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,3800);}
function invalidate(){state.firstCityId=null;state.firstProfile=null;state.selectedCityId=null;state.round=1;state.answerLog=[];state.feedbackReason=null;state.feedbackPicking=null;}
function updateField(key,value){state.profile[key]=value;if(!['nickname','school','major','mbti','stage'].includes(key))invalidate();save();}
const input=(key,label,placeholder='',type='text')=>`<label class="field"><span>${label}<span class="optional">选填</span></span><input type="${type}" data-field="${key}" value="${escape(state.profile[key])}" ${type==='number'?'min="1" max="100000"':'maxlength="60"'} placeholder="${escape(placeholder)}" autocomplete="off"></label>`;
function chips(key,items,multiple=false){return `<div class="chips" role="group" aria-label="${escape(key)}">${Object.entries(items).map(([id,label])=>`<button class="select-chip" data-action="${multiple?'multi':'choose'}" data-field="${key}" data-value="${escape(id)}" aria-pressed="${multiple?state.profile[key].includes(id):String(state.profile[key])===id}">${escape(label)}</button>`).join('')}</div>`;}
function guidePane(){const route=state.route;const titles={profile:'找一座，<br>让你愿意<br><em>留下的城市。</em>',portrait:'城市还没定，<br><em>想过的日子<br>先清楚一点。</em>',first:'这座城市，<br><em>你想认识吗？</em>',question:'心动也好，<br>犹豫也好，<br><em>都很有用。</em>',result:'下一站，<br><em>有点期待。</em>'};return `<aside class="guide-pane"><div class="eyebrow">JOY CITY / 毕业第一站</div><h1>${titles[route]}</h1><p class="intro">给想做 AI 产品的你。<br>从一周怎么过，找到想去的城。</p><div class="guide-chooser" role="group" aria-label="选择推荐视角"><button class="guide-choice" data-action="guide" data-value="dog" aria-pressed="${state.profile.guide==='dog'}">ENFP 小狗<small>生活心动</small></button><button class="guide-choice" data-action="guide" data-value="cat" aria-pressed="${state.profile.guide==='cat'}">INTP 小猫<small>职业发展</small></button></div><div class="guide-portrait asset-ready"><img src="/assets/guide-${state.profile.guide}.png" alt="${dog('拿着车票的黑白德文猫','拿着车票的活泼线条小狗')}" width="320" height="320"></div><div class="guide-note"><span class="note-sign">“</span><div>${dog('我先看你想怎样做 AI，再把生活的代价摆出来。','我先看看，什么样的普通一天会让你开心。')}</div></div><div class="guide-name">${guideName()} / 你的城市介绍人</div><div class="waypoints">${['选日常','看画像','认识城市','收好车票'].map((x,i)=>`<span class="${(route==='profile'?0:route==='portrait'?1:route==='result'?3:2)===i?'is-current':''}"><i>${i+1}</i>${x}</span>`).join('')}</div></aside>`;}
function folder(content){return `<section class="file-folder" aria-label="城市匹配"><div class="folder-tabs"><span class="active">${({profile:'一份生活意向',portrait:'我理解的你',first:'第一次介绍',question:'再确认一件事',result:'你的城市车票'})[state.route]}</span><span>JOY CITY</span></div><div class="form-sheet">${content}</div></section>`;}
function choices(items,action,selected,dimension=''){return `<div class="choice-list scene-choices">${items.map((o,i)=>`<button class="choice-card" data-action="${action}" data-value="${o.id}" data-dimension="${dimension}" aria-pressed="${selected===o.id}"><span class="option-number">0${i+1}</span><span class="option-copy"><b>${escape(o.label)}</b>${o.description?`<span>${escape(o.description)}</span>`:''}</span><span class="option-mark" aria-hidden="true">${selected===o.id?'✓':'↗'}</span></button>`).join('')}</div>`;}
function profilePage(){const p=state.profile,page=state.page,d=JOY_CONFIG.dimensions[page-1];let body='';
 if(page===0)body=`<div class="welcome-label">给 AI 行业新人的城市介绍所</div><h2>先说说，你想做什么。</h2><p class="sheet-intro">接下来选 5 个生活场景，再看看哪座城市值得认识。没有标准答案，也不用填满。</p>${choices(JOY_CONFIG.aiRoles,'role',p.aiRole)}<details class="optional-details"><summary>愿意的话，再介绍一下自己<span>选填</span></summary><div class="details-inner">${input('nickname','怎么称呼你','一个昵称就好')}<div class="fields-two">${input('school','毕业／在读院校','不影响城市排序')}${input('major','所学专业','不影响城市排序')}</div>${input('mbti','你的 MBTI','不知道也没关系')}<p class="fine-print">这些只用于介绍自己。我们不会按学校、年龄或人格标签给你分配城市。</p></div></details>`;
 else if(d)body=`<div class="scene-caption"><span>SCENE 0${page}</span><span>${escape(d.label)}</span></div><h2>${escape(d.question)}</h2><p class="sheet-intro">${escape(d.why)}</p>${choices(d.options,'scene',p.joy[d.id],d.id)}<div class="selected-echo" aria-live="polite">${p.joy[d.id]?`记下了：${escape(d.options.find(o=>o.id===p.joy[d.id]).portrait)}。`:'按你现在的生活来选，之后可以改。'}</div>`;
 else body=`<div class="scene-caption"><span>ONE LAST THING</span><span>天气与现实条件</span></div><h2>有些天气，会影响一整天。</h2><p class="sheet-intro">你想尽量避开哪些？可以多选，也可以都不选。</p>${chips('climateAvoids',climateNames,true)}${p.climateAvoids.length?`<div class="climate-limit"><span>对你来说，这是…</span>${chips('hardClimate',{'false':'尽量避开','true':'明确不能接受'})}</div>`:''}<details class="optional-details"><summary>已经想好房租和通勤了？<span>选填</span></summary><div class="details-inner"><div class="fields-two">${input('rentBudget','每月房租上限 / 元','如：4000','number')}${input('maxCommuteMinutes','单程通勤上限 / 分钟','如：30','number')}</div><div class="field"><span>居住方式</span>${chips('housingType',{'unknown':'还没定','primary-shared':'合租主卧','alone':'整租独住','either':'都可以'})}</div>${input('homeCity','重要的人所在城市','仅记录，还需核验实际往返')}<p class="fine-print">记录为待核验条件。现有城市资料不能保证具体房源和通勤满足要求。</p></div></details>`;
 return folder(`<div class="sheet-meta"><span>${page===0?'START WITH YOU':`LIFE FILE / 0${page}`}</span><span class="stamp">只记你确认的</span></div><div class="scene-progress" aria-label="第 ${page+1} 步，共 7 步">${Array.from({length:7},(_,i)=>`<i class="${i<=page?'done':''}"></i>`).join('')}</div>${body}<div class="form-actions"><button class="quiet-button" data-action="${page?'previous-profile':'preview-portrait'}">${page?'上一个':'直接看看画像'}</button><button class="primary" data-action="next-profile">${page===6?'看看我的生活画像':'继续'} <span aria-hidden="true">→</span></button></div><div class="step-footer"><span>${page+1} / 7 · 随时可以修改</span><span>${storageAvailable?'仅在本机保存':'暂时无法保存进度'}</span></div>`);}
function portraitPage(){const p=buildPortrait(state.profile);return folder(`<div class="sheet-meta"><span>YOUR LIFE, IN WORDS</span><span class="stamp">请你过目</span></div><h2>${state.profile.nickname?escape(state.profile.nickname)+'，':''}这是你想过的日子吗？</h2><p class="sheet-intro">每一句都来自你的选择。哪里不对，点开就能改。</p><div class="portrait-lines">${JOY_CONFIG.dimensions.map((d,i)=>{const line=p.lines.find(x=>x.dimension===d.id);return `<button data-action="edit-dimension" data-value="${i+1}"><span>${d.label}</span><b>${escape(line?.text||'还没想好，先留空')}</b><i aria-hidden="true">↗</i></button>`;}).join('')}</div>${state.profile.climateAvoids.length?`<p class="portrait-climate">${state.profile.hardClimate?'明确不能接受':'希望尽量避开'}：${state.profile.climateAvoids.map(k=>climateNames[k]).join('、')} <button class="quiet-button" data-action="edit-dimension" data-value="6">修改</button></p>`:''}<div class="portrait-footnote">${escape(p.caveat)}</div><button class="primary full" data-action="confirm-portrait">${p.items.length?'是的，介绍一座城市给我':'先认识城市，再想想自己'} <span aria-hidden="true">→</span></button><button class="quiet-button" data-action="edit-dimension" data-value="0">补充 AI 方向与背景</button>`);}
function currentQuestion(){return getNextQuestion(state.profile,rankCities(state.profile,cities),2);}
function questionPage(){const q=currentQuestion();return folder(`<div class="sheet-meta"><span>A LITTLE CLOSER / 第二轮</span><span class="stamp">根据刚才的反馈</span></div><div class="question-count">${escape(feedNames[state.feedbackReason]||'再比较一下')}</div><h2>${escape(q.title)}</h2><p class="sheet-intro">${escape(q.why)}</p>${choices(q.options,'answer',null)}<div class="form-actions"><button class="quiet-button" data-action="back-first">回去看看城市</button><button class="quiet-button" data-action="skip-question">先保留现在的想法 →</button></div>`);}
function rankingNotice(r){if(!r.ranked.length)return '';const top=r.ranked[0];if(top.score===0)return `<div class="result-limit">目前还不足以替你排先后。先认识一座，再用你的反应缩小范围。</div>`;return r.ambiguous?`<p class="ranking-note">还有相近候选。这里是先了解的顺序，不是幸福概率。</p>`:'';}
function relevantReasons(result){return [...(result.reasons||[])].sort((a,b)=>(result.components.find(x=>x.key===b.key)?.weight||0)-(result.components.find(x=>x.key===a.key)?.weight||0)).slice(0,3);}
function ticket(r,final=false){const c=r.city,reasons=relevantReasons(r),portrait=c.joyPortrait;const preferred=new Set(reasons.map(x=>x.dimension));const gaps=JOY_CONFIG.dimensions.filter(d=>state.profile.joy[d.id]&&!preferred.has(d.id)&&!r.reasons.some(x=>x.dimension===d.id)).map(d=>d.label);
 return `<article class="city-ticket" aria-label="${escape(c.name)}城市车票"><div class="ticket-head"><div class="ticket-kicker"><span>${final?'YOUR JOY CITY / 候选目的地':'MEET THE CITY / 第一次介绍'}</span><span>${dog('职业发展视角','生活心动视角')}</span></div><div class="city-display"><div><h3>${escape(c.name)}</h3><div class="english">${escape(c.english)}</div></div><div class="ticket-number">${String(cities.findIndex(x=>x.id===c.id)+1).padStart(2,'0')}</div></div><p class="city-tagline">${escape(portrait?.invitation||c.tagline)}</p></div><div class="ticket-body"><div class="ticket-section-title">你可能会喜欢的部分 <small>公开资料上的整理判断</small></div>${reasons.length?reasons.map((r,i)=>`<div class="reason-row"><span class="reason-index">0${i+1}</span><div><span class="reason-preference">${escape(dimensionNames[r.dimension]||'天气偏好')}</span><p>${escape((r.key?.startsWith('climate:')?c.featureEvidence?.[r.key.slice(8)]?.note:c.joySignals?.[r.key]?.note)||r.text)}</p></div></div>`).join(''):`<p class="sheet-intro">你的偏好已记下，但现有资料还不足以支持匹配。可以先看城市资料，再补一项你在意的事。</p>`}<div class="tradeoff"><b>喜欢它，也得接受这一面</b>${escape(portrait?.frictions?.[0]||r.tradeoffs?.[0]||'喜欢的资源是否在日常可达范围，还得看工作地和住处。')}</div>${gaps.length?`<p class="gap-note">${gaps.join('、')}还无法按城市判断，暂时没有用于拉开差距。</p>`:''}<details class="evidence-details"><summary>哪些条件还需要确认</summary><ul>${(r.unknowns||[]).map(x=>`<li>${escape(x)}</li>`).join('')}</ul></details><button class="evidence-toggle" data-action="evidence" data-value="${escape(c.id)}">翻到背面，看看依据 ↗</button></div></article>`;}
function emptyPage(r){return folder(`<div class="sheet-meta">NO RUSH / 不用硬选</div><h2>这轮先不硬凑一座城市。</h2><p class="sheet-intro">保留你已经说清楚的底线。可以改偏好，也可以重新考虑之前排除的城市。</p>${r.excluded.map(x=>`<div class="excluded-row"><span>${escape(x.city.name)} · 已排除</span><button class="quiet-button" data-action="restore-city" data-value="${x.city.id}">重新考虑</button></div>`).join('')}<button class="primary full" data-action="edit-profile">回到生活画像</button>`);}
function firstPage(){const ranking=rankCities(state.profile,cities),r=ranking.ranked.find(x=>x.city.id===state.firstCityId)||ranking.ranked[0];if(!r)return emptyPage(ranking);state.firstCityId=r.city.id;if(!state.firstProfile)state.firstProfile=structuredClone(state.profile);save();return folder(`<div class="sheet-meta"><span>FIRST DATE / 城市初见</span><span class="stamp">先听听你的反应</span></div><h2>我想介绍你认识${escape(r.city.name)}。</h2>${rankingNotice(ranking)}${ticket(r)}<div class="field-title">想象在这里过一周，你的反应是？</div><div class="feedback-grid">${Object.entries(feedNames).map(([id,label])=>`<button class="${id==='heart'?'feedback-like':''}" data-action="feedback" data-value="${id}" data-city="${r.city.id}">${label} <span aria-hidden="true">${id==='heart'?'♡':'↗'}</span></button>`).join('')}</div>${state.feedbackPicking?`<div class="feedback-followup" tabindex="-1"><b>${state.feedbackPicking==='heart'?'让你心动的是哪一部分？':'你最在意的是哪一部分？'}</b><div class="chips">${[...JOY_CONFIG.dimensions,{id:'climate',label:'天气'}].map(d=>`<button class="select-chip" data-action="feedback-dimension" data-value="${d.id}" data-city="${r.city.id}">${d.label}</button>`).join('')}</div></div>`:'<p class="fine-print">反馈后只再确认一件事，看看推荐会怎样变化。</p>'}`);}
function changeExplanation(top){if(!state.firstProfile)return '按你现在确认的偏好，先了解这里。';const before={...state.firstProfile,guide:state.profile.guide};const changed=JOY_CONFIG.dimensions.filter(d=>before.joy?.[d.id]!==state.profile.joy[d.id]).map(d=>d.label);const prev=cities.find(c=>c.id===state.firstCityId);const rejected=state.profile.excludedCityIds.includes(state.firstCityId);return `${rejected&&prev?`你明确不考虑${prev.name}，已把它移出。`:changed.length?`你重新确认了${changed.join('、')}。`:'你保留了原来的生活偏好。'}${prev?.id===top.city.id?`这轮仍先看${top.city.name}，现有依据没有把它换下去。`:`这轮先了解${top.city.name}。`}`;}
function resultPage(){const ranking=rankCities(state.profile,cities);if(!ranking.ranked.length)return emptyPage(ranking);const top=ranking.ranked[0],r=ranking.ranked.find(x=>x.city.id===state.selectedCityId)||top;state.selectedCityId=r.city.id;save();const other=rankCities({...state.profile,guide:state.profile.guide==='dog'?'cat':'dog'},cities).ranked[0];return folder(`<div class="sheet-meta"><span>YOUR NEXT CHAPTER / 两轮之后</span><span class="stamp">留一点期待</span></div><h2>下一站，可以先去了解。</h2><div class="revision-note">${escape(changeExplanation(top))}</div>${rankingNotice(ranking)}${ticket(r,true)}<div class="field-title">另外两种可能，也放在这里</div><div class="shortlist">${ranking.ranked.slice(0,3).map((x,i)=>`<button data-action="select-city" data-value="${x.city.id}" aria-pressed="${r.city.id===x.city.id}"><span><b>${escape(x.city.name)}</b><small>${escape(x.city.joyPortrait?.invitation||x.city.tagline)}</small></span><span class="candidate-index">0${i+1}</span></button>`).join('')}</div><div class="other-lens"><span>${dog('如果把生活放在前面','如果把职业放在前面')}，${other?.city.id===top.city.id?'仍会先看':'会先看'}${escape(other?.city.name||'现有候选')}。</span><button class="quiet-button" data-action="guide" data-value="${state.profile.guide==='dog'?'cat':'dog'}">听听${dog('小狗','小猫')}怎么说 →</button></div><div class="share-actions"><button class="primary" data-action="share-card">收好我的城市车票 ↗</button><button class="secondary" data-action="copy-result">复制城市摘要</button></div><p class="privacy-note">只分享城市与生活关键词，个人资料留在本机。</p><div class="trial-plan"><div class="field-title">怎么知道，你会不会真的喜欢？</div>${buildTrialPlan(state.profile).map(x=>`<div><b>${escape(x.title)}</b><p>${escape(x.text)}</p></div>`).join('')}</div><div class="form-actions"><button class="quiet-button" data-action="edit-profile">再改改我的生活画像</button><button class="quiet-button" data-action="method">查看撮合规则</button></div>${ranking.excluded.length?`<details class="evidence-details"><summary>已经排除的城市</summary>${ranking.excluded.map(x=>`<div class="excluded-row"><span>${escape(x.city.name)}</span><button class="quiet-button" data-action="restore-city" data-value="${x.city.id}">重新考虑</button></div>`).join('')}</details>`:''}`);}
function render({focus=false}={}){document.body.classList.toggle('guide-dog',state.profile.guide==='dog');document.body.dataset.route=state.route;main.innerHTML=`<div class="workbench">${guidePane()}${({profile:profilePage,portrait:portraitPage,first:firstPage,question:questionPage,result:resultPage})[state.route]()}</div>`;if(focus){const h=main.querySelector('.form-sheet h2');h?.setAttribute('tabindex','-1');h?.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}}
function dialog(title,html){if(document.activeElement?.matches('button,a,input,select'))dialogOpener=document.activeElement;document.getElementById('dialog-title').textContent=title;document.getElementById('dialog-content').innerHTML=html;const d=document.getElementById('detail-dialog');if(!d.open)d.showModal();}
function sourceHTML(c){return `<div class="source-card"><h3>${escape(c.name)}</h3><p>${escape(c.joyPortrait?.invitation||c.tagline)}</p>${c.sources.map(s=>`<p><a href="${escape(safeURL(s.url))}" target="_blank" rel="noopener noreferrer">${escape(s.title)}</a><br><small>${s.published?'发布：'+escape(s.published)+' · ':''}核对：${escape(s.checked)}</small></p>`).join('')}</div>`;}
function showEvidence(id){const c=cities.find(x=>x.id===id);if(!c)return;const r=rankCities(state.profile,cities).ranked.find(x=>x.city.id===id);dialog(c.name+' · 车票背面',`<p>城市特点是公开资料上的整理判断。资源存在，不等于你每天都能用到，更不代表你一定喜欢。</p>${(r?.reasons||[]).map(x=>`<div class="source-card"><h3>${escape(dimensionNames[x.dimension]||'天气')}</h3><p>${escape(x.text)}</p><small>${escape(x.caveat||'整理判断，仍需亲自验证')}</small>${(x.sourceIds||[]).map(id=>c.sources.find(s=>s.id===id)).filter(Boolean).map(s=>`<p><a href="${escape(safeURL(s.url))}" target="_blank" rel="noopener noreferrer">${escape(s.title)}</a></p>`).join('')}</div>`).join('')}${sourceHTML(c)}`);}
function showMethod(){dialog('这份城市介绍怎么来的',`<div class="method-flow"><div><strong>01 先写下你想过的日子</strong>5 个场景形成可修改的生活画像，每句话都来自明确选择。空白不会被猜成性格。</div><div><strong>02 同一份资料，两种侧重</strong>小狗优先看生活，小猫优先看 AI 职业期待；天气底线、明确拒绝和城市事实始终相同。</div><div><strong>03 反馈后，确认一个关键选择</strong>心动或不能接受的维度会触发追问。修改后的选择重新参与排序；保持原想法时，推荐也可能不变。</div><div><strong>04 把依据和空白一起交给你</strong>有来源的线索才用于比较。未知项不补成平均值。证据少会影响排序，我们会提示相近候选，避免把顺序冒充概率。</div></div><h3>两位介绍人的分量怎么分</h3><table class="weight-table"><thead><tr><th>维度</th><th>小狗</th><th>小猫</th></tr></thead><tbody>${JOY_CONFIG.dimensions.map(d=>`<tr><td>${d.label}</td><td>${JOY_CONFIG.weights.dog[d.id]*100}%</td><td>${JOY_CONFIG.weights.cat[d.id]*100}%</td></tr>`).join('')}</tbody></table><p>选了天气避开项后，天气占 20%，上述分量按比例缩至 80%。这是可审查的初版产品规则，尚未经过用户结果验证。</p><p>现有 ${cities.length} 城资料支持探索。关系质量、工作稳定性、个人可承受的变化、实际房源与通勤仍不能靠城市整体资料判断。AI 方向用于界定服务范围，暂时没有按具体岗位做就业概率匹配。</p><p>MBTI、年龄、学校和星座不参与排序。网页版使用透明规则，未调用大模型；原生参赛版的 Agent 接入状态单独记录。</p>`);}
function showPrivacy(){dialog('你的资料留在哪里',`<p>资料只保存在这台设备的浏览器中，用于恢复进度。这个网页版没有把资料发送给远端模型。</p><p>分享卡和复制摘要只包含城市、公开城市介绍和所选生活关键词，不包含姓名、院校、年龄、预算、重要的人位置或自由文本。</p><p>升级时保留旧资料备份；清除会连同备份一起删除。</p><button class="secondary" data-action="confirm-reset">清除本机资料</button>`);}
function wrapCanvas(ctx,text,x,y,maxWidth,lineHeight){let line='';for(const char of text){if(ctx.measureText(line+char).width>maxWidth&&line){ctx.fillText(line,x,y);line=char;y+=lineHeight;}else line+=char;}if(line)ctx.fillText(line,x,y);return y+lineHeight;}
function rounded(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();}
async function createShare(){
  const ranking=rankCities(state.profile,cities);const r=ranking.ranked.find(x=>x.city.id===state.selectedCityId)||ranking.ranked[0];if(!r)return;
  const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1440;const ctx=canvas.getContext('2d');
  const accent=state.profile.guide==='dog'?'#c65225':'#2e50c8';ctx.fillStyle='#f7f5ef';ctx.fillRect(0,0,1080,1440);
  ctx.fillStyle='#fffdf8';rounded(ctx,64,64,952,1312,32);ctx.strokeStyle='#d6d8cd';ctx.lineWidth=2;ctx.stroke();
  ctx.fillStyle=accent;ctx.font='600 25px "PingFang SC",sans-serif';ctx.fillText('毕业第一站 / MY JOY CITY',112,136);
  ctx.fillStyle='#6b706a';ctx.font='24px "PingFang SC",sans-serif';ctx.fillText('我想先去了解的城市',112,238);
  ctx.fillStyle='#202b29';ctx.font='600 164px "Songti SC",serif';ctx.fillText(r.city.name,104,435);ctx.font='26px sans-serif';ctx.fillStyle='#6b706a';ctx.fillText(r.city.english,114,497);
  ctx.strokeStyle='#c7c9be';ctx.setLineDash([9,9]);ctx.beginPath();ctx.moveTo(64,555);ctx.lineTo(1016,555);ctx.stroke();ctx.setLineDash([]);
  ctx.fillStyle=accent;ctx.font='500 34px "PingFang SC",sans-serif';let y=wrapCanvas(ctx,(r.city.joyPortrait?.invitation||r.city.tagline),112,630,835,53);
  const tags=buildPortrait(state.profile).lines.filter(x=>['novelty','recovery'].includes(x.dimension)).map(x=>x.text);ctx.font='27px "PingFang SC",sans-serif';ctx.fillStyle='#475344';y=wrapCanvas(ctx,tags.length?'想把这些留在生活里：'+tags.join(' · '):'给工作留一个方向，也给生活留一点空间。',112,y+24,795,44);
  const img=new Image();img.src='/assets/guide-'+state.profile.guide+'.png';await img.decode();ctx.drawImage(img,600,865,360,360);
  ctx.fillStyle='#202b29';ctx.font='500 37px "PingFang SC",sans-serif';wrapCanvas(ctx,'城市还没定，\n想过的日子清楚了一点。'.replace('\n',''),112,1010,440,60);
  ctx.font='22px "PingFang SC",sans-serif';ctx.fillStyle='#6b706a';ctx.fillText('一张候选车票，不是一锤定音。',112,1228);ctx.fillText('城市探索版 · 候选建议，不是幸福概率',112,1300);
  const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw new Error('图片生成失败');if(shareURL)URL.revokeObjectURL(shareURL);shareURL=URL.createObjectURL(blob);
  dialog('收好你的城市车票',`<img class="share-preview-image" src="${shareURL}" alt="${escape(r.city.name)}城市候选分享卡"><a class="primary" style="display:block;text-align:center;text-decoration:none" href="${shareURL}" download="毕业第一站-${escape(r.city.name)}.png">保存城市车票</a><p class="privacy-note">这张卡不含院校、年龄、预算和他人信息。</p>`);
}
async function copyResult(){const r=rankCities(state.profile,cities).ranked.find(x=>x.city.id===state.selectedCityId)||rankCities(state.profile,cities).ranked[0];if(!r)return;const text=`我的 Joy City｜先了解${r.city.name}\n${r.city.joyPortrait?.invitation||r.city.tagline}\n${buildPortrait(state.profile).lines.filter(x=>['novelty','recovery'].includes(x.dimension)).map(x=>x.text).join(' · ')}\n这是一份探索建议，不是幸福概率。`;try{await navigator.clipboard.writeText(text);toast('摘要复制好了。');}catch{dialog('复制城市摘要',`<label class="field"><span>选中文字复制</span><textarea readonly rows="8">${escape(text)}</textarea></label>`);}}
function move(route){state.route=route;save();render({focus:true});}
function submitFeedback(city,reason,dimension){state.profile=applyFeedback(state.profile,city,reason,{dimension});state.feedbackReason=reason;state.feedbackPicking=null;state.round=2;move('question');}
document.addEventListener('input',e=>{const k=e.target.dataset.field;if(k&&e.target.matches('input'))updateField(k,e.target.type==='number'?(Number(e.target.value)>0?Number(e.target.value):null):e.target.value);});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,v=b.dataset.value;
 try{
 if(a==='guide'){state.profile.guide=v==='cat'?'cat':'dog';state.selectedCityId=null;if(state.route==='first'){state.firstCityId=null;state.firstProfile=structuredClone(state.profile);}save();render();return;}
 if(a==='role'){updateField('aiRole',v);render();return;}
 if(a==='scene'){const d=JOY_CONFIG.dimensions.find(x=>x.id===b.dataset.dimension);if(!d?.options.some(x=>x.id===v))return;state.profile.joy[d.id]=v;state.profile.answerSources['joy.'+d.id]={questionId:'profile-'+d.id,optionId:v,value:v};invalidate();save();render();return;}
 if(a==='choose'){updateField(b.dataset.field,b.dataset.field==='hardClimate'?v==='true':v);render();return;}
 if(a==='multi'){const k=b.dataset.field,list=state.profile[k];updateField(k,list.includes(v)?list.filter(x=>x!==v):[...list,v]);render();return;}
 if(a==='next-profile'){if(state.page===6)move('portrait');else{state.page++;save();render({focus:true});}return;}
 if(a==='previous-profile'){state.page=Math.max(0,state.page-1);save();render({focus:true});return;}
 if(a==='preview-portrait'||a==='edit-profile'){move('portrait');return;}
 if(a==='edit-dimension'){state.page=Number(v);move('profile');return;}
 if(a==='confirm-portrait'){invalidate();state.profile.confirmations=[];move('first');return;}
 if(a==='feedback'){if(['heart','unbearable'].includes(v)){state.feedbackPicking=v;render();const f=main.querySelector('.feedback-followup');f?.focus({preventScroll:true});f?.scrollIntoView({block:'nearest',behavior:'smooth'});}else submitFeedback(b.dataset.city,v);return;}
 if(a==='feedback-dimension'){submitFeedback(b.dataset.city,state.feedbackPicking,v);return;}
 if(a==='back-first'){move('first');return;}
 if(a==='answer'){const q=currentQuestion(),o=q.options.find(x=>x.id===v);state.profile=applyAnswer(state.profile,q,v);state.answerLog.push({round:2,id:q.id,label:o.label});state.selectedCityId=null;move('result');return;}
 if(a==='skip-question'){state.selectedCityId=null;move('result');return;}
 if(a==='select-city'){state.selectedCityId=v;save();render();return;}
 if(a==='restore-city'){state.profile.excludedCityIds=state.profile.excludedCityIds.filter(x=>x!==v);state.profile.feedback=state.profile.feedback.filter(x=>!(x.cityId===v&&x.reasonId==='not-this-city'));state.selectedCityId=null;save();render();return;}
 if(a==='method'){showMethod();return;}
 if(a==='data'){dialog('城市资料与来源',`<p>当前覆盖 ${cities.length} 座城市；城市相处说明是资源线索，不是居民人格。初版分档为人工整理，尚未验证喜欢概率。</p>${cities.map(sourceHTML).join('')}`);return;}
 if(a==='evidence'){showEvidence(v);return;}
 if(a==='privacy'){showPrivacy();return;}
 if(a==='confirm-reset'){dialog('清除这台设备上的资料？','<p>填写的资料、选择、拒绝记录和旧版备份都会被清除。</p><button class="primary" data-action="reset">确认清除</button>');return;}
 if(a==='reset'){state=freshState();try{localStorage.removeItem(KEY);localStorage.removeItem(BACKUP);}catch{}document.getElementById('detail-dialog').close();render({focus:true});toast('本机资料已清除。');return;}
 if(a==='close-dialog'){document.getElementById('detail-dialog').close();return;}
 if(a==='share-card'){dialogOpener=b;b.disabled=true;await createShare();b.disabled=false;return;}
 if(a==='copy-result'){await copyResult();return;}
 }catch(error){console.error(error);b.disabled=false;toast('刚才这一步没有完成，资料还在。请再试一次。');}
});
document.getElementById('detail-dialog').addEventListener('close',()=>{const target=dialogOpener?.isConnected&&!dialogOpener.disabled?dialogOpener:main.querySelector('h2');if(target){if(!target.matches('button,a,input,select'))target.setAttribute('tabindex','-1');target.focus({preventScroll:true});}dialogOpener=null;});
document.getElementById('detail-dialog').addEventListener('click',e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.currentTarget.close();}});
async function start(){readState();try{const response=await fetch('/data/cities.json');if(!response.ok)throw new Error('城市资料暂未准备好');cities=await response.json();if(!Array.isArray(cities)||!cities.length)throw new Error('城市资料格式错误');document.querySelector('.header-edition').textContent=`${cities.length} 座城市 · 找到你的 Joy City`;render();}catch(error){main.innerHTML=`<div class="form-sheet"><h1>城市资料暂时没加载出来。</h1><p>本机资料还在，请稍后刷新。</p><p class="error-note">${escape(error.message)}</p><button class="primary" onclick="location.reload()">重新加载</button></div>`;}}
start();
